require("config.highlights")
require("config.mappings")
require("config.lazy")
require("config.config")
require("config.diagnostics")
require("config.theme_switcher")
require("config.provider_switcher")
require("config.cmp")