local M = {}

local palettes = {
  night = {
    background = "dark",
    base = "#0b0b0f",
    mantle = "#111116",
    crust = "#07070a",
    surface0 = "#18171c",
    surface1 = "#242229",
    surface2 = "#2d2a31",
    overlay0 = "#514b53",
    overlay1 = "#736b72",
    overlay2 = "#a8a0a6",
    subtext0 = "#a8a0a6",
    subtext1 = "#d8d2ce",
    text = "#f4f0e8",
    bright = "#fffaf3",
    border = "#343039",
    border_variant = "#6e2638",
    border_focus = "#d6b56d",
    border_disabled = "#242229",
    icon = "#d8d2ce",
    info_bg = "#1b2431",
    hint_bg = "#1b2926",
    warning_bg = "#3d2612",
    error_bg = "#3d1118",
    created_bg = "#3c202b",
    modified_bg = "#3a2c15",
    selection = "#3c202b",
    visual = "#6e2638",
    red = "#d84d6f",
    peach = "#ff7892",
    yellow = "#d6b56d",
    green = "#9ba66f",
    blue = "#9fb0c8",
    sky = "#b8c6bf",
    teal = "#b8c6bf",
    mauve = "#f2b8cc",
    pink = "#f2b8cc",
    lavender = "#c3d0e4",
    string_special = "#f7d8e3",
  },
  light = {
    background = "light",
    base = "#f3dde6",
    mantle = "#ead0dc",
    crust = "#e3c4d0",
    surface0 = "#f8e8ee",
    surface1 = "#e3c4d0",
    surface2 = "#d9b5c3",
    overlay0 = "#a98c9a",
    overlay1 = "#806b76",
    overlay2 = "#5f4f59",
    subtext0 = "#5f4f59",
    subtext1 = "#3e343a",
    text = "#171316",
    bright = "#080608",
    border = "#d2aebb",
    border_variant = "#b4862b",
    border_focus = "#8f6518",
    border_disabled = "#dfc2cd",
    icon = "#3e343a",
    info_bg = "#cad4df",
    hint_bg = "#c9d8d3",
    warning_bg = "#e5d09a",
    error_bg = "#e8bdc8",
    created_bg = "#deb8c7",
    modified_bg = "#e5d09a",
    selection = "#deb8c7",
    visual = "#d894aa",
    red = "#9f1f42",
    peach = "#7e1732",
    yellow = "#7d5b12",
    green = "#5d6530",
    blue = "#405a78",
    sky = "#405f57",
    teal = "#405f57",
    mauve = "#8f2447",
    pink = "#8f2447",
    lavender = "#2f445d",
    string_special = "#6f1a36",
  },
}

local function set(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
  set(group, { link = target })
end

local function apply(groups)
  for _, group_set in ipairs(groups) do
    for group, opts in pairs(group_set) do
      set(group, opts)
    end
  end
end

local function terminal(p)
  return {
    terminal_color_0 = p.mantle,
    terminal_color_1 = p.red,
    terminal_color_2 = p.green,
    terminal_color_3 = p.yellow,
    terminal_color_4 = p.blue,
    terminal_color_5 = p.pink,
    terminal_color_6 = p.teal,
    terminal_color_7 = p.text,
    terminal_color_8 = p.overlay1,
    terminal_color_9 = p.peach,
    terminal_color_10 = p.green,
    terminal_color_11 = p.yellow,
    terminal_color_12 = p.lavender,
    terminal_color_13 = p.mauve,
    terminal_color_14 = p.sky,
    terminal_color_15 = p.bright,
  }
end

local function editor(p)
  return {
    ColorColumn = { bg = p.surface0 },
    Conceal = { fg = p.overlay1 },
    Cursor = { fg = p.base, bg = p.pink },
    CursorColumn = { bg = p.mantle },
    CursorLine = { bg = p.surface0 },
    Directory = { fg = p.yellow },
    EndOfBuffer = { fg = p.surface1 },
    ErrorMsg = { fg = p.red, bold = true, italic = true },
    Folded = { fg = p.yellow, bg = p.surface1 },
    FoldColumn = { fg = p.overlay1, bg = p.base },
    SignColumn = { fg = p.overlay1, bg = p.base },
    LineNr = { fg = p.overlay1, bg = p.base },
    CursorLineNr = { fg = p.yellow, bg = p.surface0, bold = true },
    MatchParen = { fg = p.yellow, bg = p.surface1, bold = true },
    ModeMsg = { fg = p.text, bold = true },
    MoreMsg = { fg = p.yellow },
    NonText = { fg = p.overlay0 },
    Normal = { fg = p.text, bg = p.base },
    NormalNC = { fg = p.text, bg = p.base },
    NormalFloat = { fg = p.text, bg = p.base },
    FloatBorder = { fg = p.border_variant, bg = "NONE" },
    FloatTitle = { fg = p.yellow, bg = p.base, bold = true },
    FloatFooter = { fg = p.overlay2, bg = p.base },
    FloatShadow = { bg = p.crust, blend = 80 },
    FloatShadowThrough = { bg = p.crust, blend = 100 },
    Pmenu = { fg = p.overlay2, bg = p.base },
    PmenuSel = { fg = p.text, bg = p.selection, bold = true },
    PmenuKind = { fg = p.pink, bg = p.base },
    PmenuKindSel = { fg = p.pink, bg = p.selection, bold = true },
    PmenuExtra = { fg = p.overlay1, bg = p.base },
    PmenuExtraSel = { fg = p.overlay2, bg = p.selection },
    PmenuSbar = { bg = p.surface0 },
    PmenuThumb = { bg = p.overlay0 },
    Question = { fg = p.yellow },
    QuickFixLine = { bg = p.selection, bold = true },
    Search = { fg = p.base, bg = p.yellow },
    IncSearch = { fg = p.base, bg = p.peach },
    CurSearch = { fg = p.base, bg = p.red },
    SpecialKey = { fg = p.overlay0 },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.yellow, undercurl = true },
    SpellLocal = { sp = p.blue, undercurl = true },
    SpellRare = { sp = p.yellow, undercurl = true },
    StatusLine = { fg = p.text, bg = p.mantle },
    StatusLineNC = { fg = p.overlay1, bg = p.mantle },
    TabLine = { fg = p.overlay1, bg = p.mantle },
    TabLineSel = { fg = p.base, bg = p.red, bold = true },
    TabLineFill = { bg = p.base },
    TermCursor = { fg = p.base, bg = p.pink },
    TermCursorNC = { fg = p.base, bg = p.overlay2 },
    Title = { fg = p.yellow, bold = true },
    Visual = { bg = p.visual },
    WarningMsg = { fg = p.yellow },
    Whitespace = { fg = p.surface1 },
    WildMenu = { fg = p.text, bg = p.selection },
    WinBar = { fg = p.pink, bg = p.base },
    WinBarNC = { fg = p.overlay1, bg = p.base },
    WinSeparator = { fg = p.border, bg = p.base },
    MsgSeparator = { fg = p.border, bg = p.base },
  }
end

local function syntax(p)
  return {
    Comment = { fg = p.overlay1, italic = true },
    SpecialComment = { fg = p.overlay2, italic = true },
    Constant = { fg = p.yellow },
    String = { fg = p.yellow },
    Character = { fg = p.yellow },
    Number = { fg = p.yellow },
    Float = { fg = p.yellow },
    Boolean = { fg = p.red },
    Identifier = { fg = p.text },
    Function = { fg = p.pink },
    Statement = { fg = p.red },
    Conditional = { fg = p.red },
    Repeat = { fg = p.red },
    Label = { fg = p.yellow },
    Operator = { fg = p.red },
    Keyword = { fg = p.red },
    Exception = { fg = p.red },
    PreProc = { fg = p.red },
    Include = { fg = p.red },
    Define = { fg = p.red },
    Macro = { fg = p.red },
    PreCondit = { fg = p.red },
    StorageClass = { fg = p.red },
    Structure = { fg = p.yellow },
    Special = { fg = p.pink },
    Type = { fg = p.yellow },
    Typedef = { fg = p.yellow },
    SpecialChar = { fg = p.pink },
    Tag = { fg = p.red, bold = true },
    Delimiter = { fg = p.overlay2 },
    Debug = { fg = p.pink },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Error = { fg = p.red },
    Todo = { fg = p.base, bg = p.yellow, bold = true },
    qfLineNr = { fg = p.yellow },
    qfFileName = { fg = p.yellow },
    Added = { fg = p.pink },
    Changed = { fg = p.yellow },
    Removed = { fg = p.red },
    diffAdded = { fg = p.pink },
    diffRemoved = { fg = p.red },
    diffChanged = { fg = p.yellow },
    DiffAdd = { fg = p.pink, bg = p.created_bg },
    DiffChange = { fg = p.yellow, bg = p.modified_bg },
    DiffDelete = { fg = p.red, bg = p.error_bg },
    DiffText = { fg = p.yellow, bg = p.surface1 },
    healthError = { fg = p.red },
    healthSuccess = { fg = p.text },
    healthWarning = { fg = p.yellow },
    markdownHeadingDelimiter = { fg = p.yellow, bold = true },
    markdownCode = { fg = p.yellow },
    markdownCodeBlock = { fg = p.yellow },
    markdownLinkText = { fg = p.yellow, underline = true },

    htmlTag = { fg = p.subtext1 },
    htmlEndTag = { fg = p.subtext1 },
    htmlTagName = { fg = p.red },
    htmlArg = { fg = p.yellow, italic = true },
    htmlString = { fg = p.yellow },
    tsxTag = { fg = p.subtext1 },
    tsxCloseTag = { fg = p.subtext1 },
    tsxCloseString = { fg = p.subtext1 },
    tsxTagName = { fg = p.pink },
    tsxIntrinsicTagName = { fg = p.red },
    tsxAttrib = { fg = p.yellow, italic = true },
    tsxEqual = { fg = p.red },
    tsxString = { fg = p.yellow },

    jsonKeyword = { fg = p.pink },
    jsonKeywordMatch = { fg = p.overlay2 },
    jsonString = { fg = p.yellow },
    jsonStringMatch = { fg = p.yellow },
    jsonEscape = { fg = p.yellow },
    jsonNumber = { fg = p.yellow },
    jsonBoolean = { fg = p.red },
    jsonNull = { fg = p.yellow },
    jsonBraces = { fg = p.subtext1 },
    jsonNoise = { fg = p.overlay2 },
    jsonQuote = { fg = p.overlay2 },
    jsonPadding = { fg = p.red },
    jsonNumError = { fg = p.red, undercurl = true },
    jsonCommentError = { fg = p.red, undercurl = true },
    jsonSemicolonError = { fg = p.red, undercurl = true },
    jsonTrailingCommaError = { fg = p.red, undercurl = true },
    jsonMissingCommaError = { fg = p.red, undercurl = true },
    jsonStringSQError = { fg = p.red, undercurl = true },
    jsonNoQuotesError = { fg = p.red, undercurl = true },
    jsonTripleQuotesError = { fg = p.red, undercurl = true },

    tomlComment = { fg = p.overlay1, italic = true },
    tomlTodo = { fg = p.base, bg = p.yellow, bold = true },
    tomlTable = { fg = p.yellow, bold = true },
    tomlTableArray = { fg = p.yellow, bold = true },
    tomlTableKey = { fg = p.yellow, bold = true },
    tomlBracket = { fg = p.subtext1 },
    tomlDelimiter = { fg = p.overlay2 },
    tomlOperator = { fg = p.red },
    tomlDotInKey = { fg = p.overlay2 },
    tomlKey = { fg = p.pink },
    tomlKeyDq = { fg = p.pink },
    tomlKeySq = { fg = p.pink },
    tomlString = { fg = p.yellow },
    tomlEscape = { fg = p.yellow },
    tomlLineEscape = { fg = p.yellow },
    tomlInteger = { fg = p.yellow },
    tomlFloat = { fg = p.yellow },
    tomlBoolean = { fg = p.red },
    tomlDate = { fg = p.string_special },
  }
end

local function diagnostics(p)
  return {
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.teal },
    DiagnosticOk = { fg = p.text },
    DiagnosticVirtualTextError = { fg = p.red, bg = p.error_bg },
    DiagnosticVirtualTextWarn = { fg = p.yellow, bg = p.warning_bg },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = p.info_bg },
    DiagnosticVirtualTextHint = { fg = p.teal, bg = p.hint_bg },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.teal, undercurl = true },
    DiagnosticFloatingError = { fg = p.red },
    DiagnosticFloatingWarn = { fg = p.yellow },
    DiagnosticFloatingInfo = { fg = p.blue },
    DiagnosticFloatingHint = { fg = p.teal },
  }
end

local function lualine(p)
  local active = { fg = p.base, bg = p.red, bold = true }
  local active_side = { fg = p.red, bg = p.surface0 }
  local mid = { fg = p.text, bg = p.mantle }
  local inactive = { fg = p.overlay1, bg = p.mantle }
  local inactive_mid = { fg = p.overlay1, bg = p.base }

  return {
    FateLualineTabActive = active,
    FateLualineTabInactive = inactive,

    lualine_a_normal = active,
    lualine_a_insert = active,
    lualine_a_visual = active,
    lualine_a_replace = active,
    lualine_a_command = active,
    lualine_a_terminal = active,
    lualine_a_inactive = inactive,

    lualine_b_normal = active_side,
    lualine_b_insert = active_side,
    lualine_b_visual = active_side,
    lualine_b_replace = active_side,
    lualine_b_command = active_side,
    lualine_b_terminal = active_side,
    lualine_b_inactive = inactive_mid,

    lualine_c_normal = mid,
    lualine_c_insert = mid,
    lualine_c_visual = mid,
    lualine_c_replace = mid,
    lualine_c_command = mid,
    lualine_c_terminal = mid,
    lualine_c_inactive = inactive_mid,

    lualine_x_normal = mid,
    lualine_x_insert = mid,
    lualine_x_visual = mid,
    lualine_x_replace = mid,
    lualine_x_command = mid,
    lualine_x_terminal = mid,
    lualine_x_inactive = inactive_mid,

    lualine_y_normal = active_side,
    lualine_y_insert = active_side,
    lualine_y_visual = active_side,
    lualine_y_replace = active_side,
    lualine_y_command = active_side,
    lualine_y_terminal = active_side,
    lualine_y_inactive = inactive_mid,

    lualine_z_normal = active,
    lualine_z_insert = active,
    lualine_z_visual = active,
    lualine_z_replace = active,
    lualine_z_command = active,
    lualine_z_terminal = active,
    lualine_z_inactive = inactive,

    lualine_a_buffers_active = active,
    lualine_a_buffers_inactive = inactive,
    lualine_z_tabs_active = active,
    lualine_z_tabs_inactive = inactive,
    lualine_transparent = { fg = p.text, bg = p.base },
  }
end

local function treesitter(p)
  return {
    ["@variable"] = { fg = p.text },
    ["@variable.builtin"] = { fg = p.red },
    ["@variable.parameter"] = { fg = p.text },
    ["@variable.parameter.builtin"] = { fg = p.red },
    ["@variable.builtin.rust"] = { fg = p.red },
    ["@parameter"] = { fg = p.text },
    ["@parameter.reference"] = { fg = p.text },
    ["@variable.member"] = { fg = p.pink },
    ["@constant"] = { fg = p.yellow },
    ["@constant.builtin"] = { fg = p.yellow },
    ["@constant.macro"] = { fg = p.red },
    ["@module"] = { fg = p.text, italic = true },
    ["@module.rust"] = { fg = p.text, italic = true },
    ["@namespace"] = { fg = p.text, italic = true },
    ["@namespace.rust"] = { fg = p.text, italic = true },
    ["@label"] = { fg = p.yellow },
    ["@string"] = { fg = p.yellow },
    ["@string.documentation"] = { fg = p.overlay2 },
    ["@string.regexp"] = { fg = p.red },
    ["@string.escape"] = { fg = p.yellow },
    ["@string.special"] = { fg = p.pink },
    ["@string.special.url"] = { fg = p.yellow, underline = true },
    ["@character"] = { fg = p.yellow },
    ["@character.special"] = { fg = p.pink },
    ["@boolean"] = { fg = p.red },
    ["@number"] = { fg = p.yellow },
    ["@number.float"] = { fg = p.yellow },
    ["@type"] = { fg = p.yellow },
    ["@type.builtin"] = { fg = p.yellow },
    ["@type.definition"] = { fg = p.yellow },
    ["@attribute"] = { fg = p.yellow },
    ["@property"] = { fg = p.pink },
    ["@field"] = { fg = p.pink },
    ["@function"] = { fg = p.pink },
    ["@function.builtin"] = { fg = p.pink },
    ["@function.call"] = { fg = p.pink },
    ["@function.macro"] = { fg = p.red },
    ["@function.method"] = { fg = p.pink },
    ["@function.method.call"] = { fg = p.pink },
    ["@method"] = { fg = p.pink },
    ["@method.call"] = { fg = p.pink },
    ["@constructor"] = { fg = p.yellow },
    ["@operator"] = { fg = p.red },
    ["@keyword"] = { fg = p.red },
    ["@keyword.modifier"] = { fg = p.red },
    ["@keyword.modifier.rust"] = { fg = p.red },
    ["@keyword.storage"] = { fg = p.red },
    ["@keyword.storage.rust"] = { fg = p.red },
    ["@keyword.mutable.rust"] = { fg = p.red },
    ["@storageclass"] = { fg = p.red },
    ["@storageclass.rust"] = { fg = p.red },
    ["@keyword.type"] = { fg = p.red },
    ["@keyword.coroutine"] = { fg = p.red },
    ["@keyword.function"] = { fg = p.red },
    ["@keyword.operator"] = { fg = p.red },
    ["@keyword.import"] = { fg = p.red },
    ["@keyword.repeat"] = { fg = p.red },
    ["@keyword.return"] = { fg = p.red },
    ["@keyword.debug"] = { fg = p.red },
    ["@keyword.exception"] = { fg = p.red },
    ["@keyword.conditional"] = { fg = p.red },
    ["@keyword.directive"] = { fg = p.red },
    ["@punctuation.delimiter"] = { fg = p.overlay2 },
    ["@punctuation.bracket"] = { fg = p.subtext1 },
    ["@punctuation.special"] = { fg = p.red },
    ["@comment"] = { fg = p.overlay1, italic = true },
    ["@comment.documentation"] = { fg = p.overlay2, italic = true },
    ["@markup"] = { fg = p.text },
    ["@markup.strong"] = { fg = p.red, bold = true },
    ["@markup.italic"] = { fg = p.red, italic = true },
    ["@markup.strikethrough"] = { fg = p.text, strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = p.yellow, bold = true },
    ["@markup.quote"] = { fg = p.pink },
    ["@markup.link"] = { fg = p.yellow },
    ["@markup.link.label"] = { fg = p.yellow },
    ["@markup.link.url"] = { fg = p.yellow, underline = true },
    ["@markup.raw"] = { fg = p.yellow },
    ["@markup.list"] = { fg = p.yellow },
    ["@markup.list.checked"] = { fg = p.pink },
    ["@markup.list.unchecked"] = { fg = p.overlay1 },
    ["@diff.plus"] = { fg = p.pink },
    ["@diff.minus"] = { fg = p.red },
    ["@diff.delta"] = { fg = p.yellow },
    ["@tag"] = { fg = p.red },
    ["@tag.builtin"] = { fg = p.red },
    ["@tag.attribute"] = { fg = p.yellow, italic = true },
    ["@tag.delimiter"] = { fg = p.red },

    ["@property.json"] = { fg = p.pink },
    ["@string.json"] = { fg = p.yellow },
    ["@string.escape.json"] = { fg = p.yellow },
    ["@number.json"] = { fg = p.yellow },
    ["@boolean.json"] = { fg = p.red },
    ["@constant.builtin.json"] = { fg = p.yellow },
    ["@punctuation.delimiter.json"] = { fg = p.overlay2 },
    ["@punctuation.bracket.json"] = { fg = p.subtext1 },
    ["@lsp.type.property.json"] = { fg = p.pink },
    ["@lsp.type.string.json"] = { fg = p.yellow },
    ["@lsp.type.number.json"] = { fg = p.yellow },
    ["@lsp.type.boolean.json"] = { fg = p.red },

    ["@property.toml"] = { fg = p.pink },
    ["@string.toml"] = { fg = p.yellow },
    ["@string.escape.toml"] = { fg = p.yellow },
    ["@string.special.toml"] = { fg = p.string_special },
    ["@number.toml"] = { fg = p.yellow },
    ["@number.float.toml"] = { fg = p.yellow },
    ["@boolean.toml"] = { fg = p.red },
    ["@operator.toml"] = { fg = p.red },
    ["@punctuation.delimiter.toml"] = { fg = p.overlay2 },
    ["@punctuation.bracket.toml"] = { fg = p.subtext1 },

    ["@variable.member.javascript"] = { fg = p.pink },
    ["@property.javascript"] = { fg = p.pink },
    ["@function.javascript"] = { fg = p.pink },
    ["@function.call.javascript"] = { fg = p.pink },
    ["@function.method.javascript"] = { fg = p.pink },
    ["@function.method.call.javascript"] = { fg = p.pink },
    ["@function.builtin.javascript"] = { fg = p.pink },
    ["@constructor.javascript"] = { fg = p.yellow },
    ["@type.javascript"] = { fg = p.yellow },
    ["@type.builtin.javascript"] = { fg = p.yellow },
    ["@module.javascript"] = { fg = p.text, italic = true },
    ["@module.builtin.javascript"] = { fg = p.text, italic = true },
    ["@constant.javascript"] = { fg = p.yellow },
    ["@constant.builtin.javascript"] = { fg = p.red },
    ["@variable.builtin.javascript"] = { fg = p.red },

    ["@variable.member.typescript"] = { fg = p.pink },
    ["@property.typescript"] = { fg = p.pink },
    ["@function.typescript"] = { fg = p.pink },
    ["@function.call.typescript"] = { fg = p.pink },
    ["@function.method.typescript"] = { fg = p.pink },
    ["@function.method.call.typescript"] = { fg = p.pink },
    ["@function.builtin.typescript"] = { fg = p.pink },
    ["@constructor.typescript"] = { fg = p.yellow },
    ["@type.typescript"] = { fg = p.yellow },
    ["@type.builtin.typescript"] = { fg = p.yellow },
    ["@module.typescript"] = { fg = p.text, italic = true },
    ["@module.builtin.typescript"] = { fg = p.text, italic = true },
    ["@constant.typescript"] = { fg = p.yellow },
    ["@constant.builtin.typescript"] = { fg = p.red },
    ["@variable.builtin.typescript"] = { fg = p.red },
    ["@keyword.import.typescript"] = { fg = p.red },
    ["@keyword.export.typescript"] = { fg = p.red },
    ["@keyword.modifier.typescript"] = { fg = p.red },
    ["@keyword.type.typescript"] = { fg = p.red },
    ["@keyword.conditional.ternary.typescript"] = { fg = p.red },
    ["@keyword.operator.typescript"] = { fg = p.red },
    ["@string.escape.typescript"] = { fg = p.yellow },
    ["@string.regexp.typescript"] = { fg = p.red },
    ["@string.special.typescript"] = { fg = p.string_special },
    ["@string.special.url.typescript"] = { fg = p.yellow, underline = true },
    ["@punctuation.delimiter.typescript"] = { fg = p.overlay2 },
    ["@punctuation.bracket.typescript"] = { fg = p.subtext1 },
    ["@punctuation.special.typescript"] = { fg = p.red },

    ["@variable.member.tsx"] = { fg = p.pink },
    ["@property.tsx"] = { fg = p.pink },
    ["@variable.parameter.tsx"] = { fg = p.text },
    ["@function.tsx"] = { fg = p.pink },
    ["@function.call.tsx"] = { fg = p.pink },
    ["@function.method.tsx"] = { fg = p.pink },
    ["@function.method.call.tsx"] = { fg = p.pink },
    ["@function.builtin.tsx"] = { fg = p.pink },
    ["@constructor.tsx"] = { fg = p.yellow },
    ["@type.tsx"] = { fg = p.yellow },
    ["@type.builtin.tsx"] = { fg = p.yellow },
    ["@module.tsx"] = { fg = p.text, italic = true },
    ["@module.builtin.tsx"] = { fg = p.text, italic = true },
    ["@constant.tsx"] = { fg = p.yellow },
    ["@constant.builtin.tsx"] = { fg = p.red },
    ["@variable.builtin.tsx"] = { fg = p.red },
    ["@keyword.import.tsx"] = { fg = p.red },
    ["@keyword.export.tsx"] = { fg = p.red },
    ["@keyword.modifier.tsx"] = { fg = p.red },
    ["@keyword.type.tsx"] = { fg = p.red },
    ["@keyword.conditional.ternary.tsx"] = { fg = p.red },
    ["@keyword.operator.tsx"] = { fg = p.red },
    ["@string.tsx"] = { fg = p.yellow },
    ["@string.escape.tsx"] = { fg = p.yellow },
    ["@string.regexp.tsx"] = { fg = p.red },
    ["@string.special.tsx"] = { fg = p.string_special },
    ["@string.special.url.tsx"] = { fg = p.yellow, underline = true },
    ["@number.tsx"] = { fg = p.yellow },
    ["@number.float.tsx"] = { fg = p.yellow },
    ["@boolean.tsx"] = { fg = p.red },
    ["@punctuation.delimiter.tsx"] = { fg = p.overlay2 },
    ["@punctuation.bracket.tsx"] = { fg = p.subtext1 },
    ["@punctuation.special.tsx"] = { fg = p.red },

    ["@tag.tsx"] = { fg = p.pink },
    ["@tag.builtin.tsx"] = { fg = p.red },
    ["@tag.attribute.tsx"] = { fg = p.yellow, italic = true },
    ["@tag.delimiter.tsx"] = { fg = p.subtext1 },
    ["@tag.jsx"] = { fg = p.pink },
    ["@tag.builtin.jsx"] = { fg = p.red },
    ["@tag.attribute.jsx"] = { fg = p.yellow, italic = true },
    ["@tag.delimiter.jsx"] = { fg = p.subtext1 },

    ["@module.go"] = { fg = p.text, italic = true },
    ["@property.go"] = { fg = p.pink },
    ["@variable.member.go"] = { fg = p.pink },
    ["@variable.parameter.go"] = { fg = p.text },
    ["@function.go"] = { fg = p.pink },
    ["@function.call.go"] = { fg = p.pink },
    ["@function.method.go"] = { fg = p.pink },
    ["@function.method.call.go"] = { fg = p.pink },
    ["@function.builtin.go"] = { fg = p.pink },
    ["@constructor.go"] = { fg = p.yellow },
    ["@type.go"] = { fg = p.yellow },
    ["@type.definition.go"] = { fg = p.yellow },
    ["@type.builtin.go"] = { fg = p.yellow },
    ["@constant.go"] = { fg = p.yellow },
    ["@constant.builtin.go"] = { fg = p.red },
    ["@operator.go"] = { fg = p.red },

    ["@lsp.type.namespace"] = { fg = p.text, italic = true },
    ["@lsp.type.namespace.rust"] = { fg = p.text, italic = true },
    ["@lsp.type.type"] = { fg = p.yellow },
    ["@lsp.type.type.rust"] = { fg = p.yellow },
    ["@lsp.type.class"] = { fg = p.yellow },
    ["@lsp.type.class.rust"] = { fg = p.yellow },
    ["@lsp.type.enum"] = { fg = p.yellow },
    ["@lsp.type.enum.rust"] = { fg = p.yellow },
    ["@lsp.type.interface"] = { fg = p.yellow },
    ["@lsp.type.interface.rust"] = { fg = p.yellow },
    ["@lsp.type.struct"] = { fg = p.yellow },
    ["@lsp.type.struct.rust"] = { fg = p.yellow },
    ["@lsp.type.parameter"] = { fg = p.text },
    ["@lsp.type.parameter.rust"] = { fg = p.text },
    ["@lsp.type.variable"] = { fg = p.text },
    ["@lsp.type.variable.rust"] = { fg = p.text },
    ["@lsp.type.property"] = { fg = p.pink },
    ["@lsp.type.property.rust"] = { fg = p.pink },
    ["@lsp.type.enumMember"] = { fg = p.yellow },
    ["@lsp.type.enumMember.rust"] = { fg = p.yellow },
    ["@lsp.type.function"] = { fg = p.pink },
    ["@lsp.type.function.rust"] = { fg = p.pink },
    ["@lsp.type.method"] = { fg = p.pink },
    ["@lsp.type.method.rust"] = { fg = p.pink },
    ["@lsp.type.keyword"] = { fg = p.red },
    ["@lsp.type.keyword.rust"] = { fg = p.red },
    ["@lsp.type.selfKeyword"] = { fg = p.red },
    ["@lsp.type.selfKeyword.rust"] = { fg = p.red },
    ["@lsp.type.selfParameter"] = { fg = p.red },
    ["@lsp.type.selfParameter.rust"] = { fg = p.red },
    ["@lsp.type.lifetime"] = { fg = p.red },
    ["@lsp.type.lifetime.rust"] = { fg = p.red },
    ["@lsp.mod.mutable"] = { fg = p.red },
    ["@lsp.mod.mutable.rust"] = { fg = p.red },
    ["@lsp.mod.defaultLibrary"] = {},
    ["@lsp.mod.defaultLibrary.rust"] = {},
    ["@lsp.typemod.variable.mutable"] = { fg = p.red },
    ["@lsp.typemod.variable.mutable.rust"] = { fg = p.red },
    ["@lsp.typemod.parameter.mutable"] = { fg = p.red },
    ["@lsp.typemod.parameter.mutable.rust"] = { fg = p.red },
    ["@lsp.typemod.selfKeyword.mutable"] = { fg = p.red },
    ["@lsp.typemod.selfKeyword.mutable.rust"] = { fg = p.red },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = p.red },
    ["@lsp.typemod.variable.defaultLibrary.rust"] = { fg = p.red },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = p.pink },
    ["@lsp.typemod.function.defaultLibrary.rust"] = { fg = p.pink },
    ["@lsp.typemod.method.defaultLibrary"] = { fg = p.pink },
    ["@lsp.typemod.method.defaultLibrary.rust"] = { fg = p.pink },

    ["@lsp.type.namespace.typescript"] = { fg = p.text, italic = true },
    ["@lsp.type.class.typescript"] = { fg = p.yellow },
    ["@lsp.type.enum.typescript"] = { fg = p.yellow },
    ["@lsp.type.interface.typescript"] = { fg = p.yellow },
    ["@lsp.type.type.typescript"] = { fg = p.yellow },
    ["@lsp.type.typeParameter.typescript"] = { fg = p.yellow },
    ["@lsp.type.parameter.typescript"] = { fg = p.text },
    ["@lsp.type.variable.typescript"] = { fg = p.text },
    ["@lsp.type.property.typescript"] = { fg = p.pink },
    ["@lsp.type.enumMember.typescript"] = { fg = p.yellow },
    ["@lsp.type.function.typescript"] = { fg = p.pink },
    ["@lsp.type.method.typescript"] = { fg = p.pink },
    ["@lsp.type.keyword.typescript"] = { fg = p.red },
    ["@lsp.typemod.variable.defaultLibrary.typescript"] = { fg = p.red },
    ["@lsp.typemod.function.defaultLibrary.typescript"] = { fg = p.pink },
    ["@lsp.typemod.method.defaultLibrary.typescript"] = { fg = p.pink },

    ["@lsp.type.namespace.typescriptreact"] = { fg = p.text, italic = true },
    ["@lsp.type.class.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.enum.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.interface.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.type.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.typeParameter.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.parameter.typescriptreact"] = { fg = p.text },
    ["@lsp.type.variable.typescriptreact"] = { fg = p.text },
    ["@lsp.type.property.typescriptreact"] = { fg = p.pink },
    ["@lsp.type.enumMember.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.function.typescriptreact"] = { fg = p.pink },
    ["@lsp.type.method.typescriptreact"] = { fg = p.pink },
    ["@lsp.type.keyword.typescriptreact"] = { fg = p.red },
    ["@lsp.type.modifier.typescriptreact"] = { fg = p.red },
    ["@lsp.type.operator.typescriptreact"] = { fg = p.red },
    ["@lsp.type.string.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.number.typescriptreact"] = { fg = p.yellow },
    ["@lsp.type.regexp.typescriptreact"] = { fg = p.red },
    ["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = { fg = p.red },
    ["@lsp.typemod.variable.readonly.typescriptreact"] = { fg = p.yellow },
    ["@lsp.typemod.property.readonly.typescriptreact"] = { fg = p.pink },
    ["@lsp.typemod.function.defaultLibrary.typescriptreact"] = { fg = p.pink },
    ["@lsp.typemod.method.defaultLibrary.typescriptreact"] = { fg = p.pink },

    ["@lsp.type.namespace.go"] = { fg = p.text, italic = true },
    ["@lsp.type.type.go"] = { fg = p.yellow },
    ["@lsp.type.parameter.go"] = { fg = p.text },
    ["@lsp.type.variable.go"] = { fg = p.text },
    ["@lsp.type.property.go"] = { fg = p.pink },
    ["@lsp.type.function.go"] = { fg = p.pink },
    ["@lsp.type.method.go"] = { fg = p.pink },
    ["@lsp.type.keyword.go"] = { fg = p.red },
    ["@lsp.typemod.variable.defaultLibrary.go"] = { fg = p.red },
    ["@lsp.typemod.function.defaultLibrary.go"] = { fg = p.pink },
    ["@lsp.typemod.method.defaultLibrary.go"] = { fg = p.pink },
  }
end

local function integrations(p)
  return {
    GitSignsAdd = { fg = p.pink },
    GitSignsChange = { fg = p.yellow },
    GitSignsDelete = { fg = p.red },
    GitSignsAddNr = { fg = p.pink },
    GitSignsChangeNr = { fg = p.yellow },
    GitSignsDeleteNr = { fg = p.red },

    CmpBorder = { link = "FloatBorder" },
    CmpDoc = { link = "NormalFloat" },
    CmpPmenu = { link = "Pmenu" },
    CmpItemAbbr = { fg = p.text },
    CmpItemAbbrDeprecated = { fg = p.overlay0, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.pink, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.pink, bold = true },
    CmpItemKind = { fg = p.pink },
    CmpItemKindVersion = { fg = p.yellow },
    CmpItemKindFeature = { fg = p.pink },
    CmpItemMenu = { fg = p.overlay1 },

    CratesNvimSearching = { fg = p.blue, bg = p.info_bg },
    CratesNvimLoading = { fg = p.blue, bg = p.info_bg },
    CratesNvimVersion = { fg = p.yellow, bg = p.warning_bg },
    CratesNvimPreRelease = { fg = p.yellow, bg = p.warning_bg },
    CratesNvimYanked = { fg = p.red, bg = p.error_bg },
    CratesNvimNoMatch = { fg = p.red, bg = p.error_bg },
    CratesNvimUpgrade = { fg = p.pink, bg = p.created_bg },
    CratesNvimError = { fg = p.red, bg = p.error_bg },
    CratesNvimPopupTitle = { fg = p.yellow, bold = true },
    CratesNvimPopupPillText = { fg = p.base, bg = p.pink },
    CratesNvimPopupPillBorder = { fg = p.pink },
    CratesNvimPopupDescription = { fg = p.overlay1, italic = true },
    CratesNvimPopupLabel = { fg = p.pink },
    CratesNvimPopupValue = { fg = p.yellow },
    CratesNvimPopupUrl = { fg = p.yellow, underline = true },
    CratesNvimPopupVersion = { fg = p.yellow },
    CratesNvimPopupPreRelease = { fg = p.yellow, bg = p.warning_bg },
    CratesNvimPopupYanked = { fg = p.red, bg = p.error_bg },
    CratesNvimPopupVersionDate = { fg = p.overlay1 },
    CratesNvimPopupFeature = { fg = p.pink },
    CratesNvimPopupEnabled = { fg = p.pink },
    CratesNvimPopupTransitive = { fg = p.blue },
    CratesNvimPopupNormalDependenciesTitle = { fg = p.yellow, bold = true },
    CratesNvimPopupBuildDependenciesTitle = { fg = p.yellow, bold = true },
    CratesNvimPopupDevDependenciesTitle = { fg = p.yellow, bold = true },
    CratesNvimPopupDependency = { fg = p.text },
    CratesNvimPopupOptional = { fg = p.overlay1, italic = true },
    CratesNvimPopupDependencyVersion = { fg = p.yellow },
    CratesNvimPopupLoading = { fg = p.blue },

    NoiceCmdlinePopup = { fg = p.text, bg = p.base },
    NoiceCmdlinePopupBorder = { fg = p.border_variant, bg = "NONE" },
    NoiceCmdlinePopupBorderSearch = { fg = p.border_variant, bg = "NONE" },
    NoiceCmdlinePopupBorderCalculator = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderCmdline = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderFilter = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderHelp = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderIncRename = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderInput = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderLua = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupTitle = { fg = p.yellow, bg = p.base, bold = true },
    NoiceCmdlineIcon = { fg = p.pink },
    NoiceCmdlineIconSearch = { fg = p.yellow },
    NoiceCmdlinePrompt = { fg = p.yellow, bold = true },
    NoicePopup = { link = "NormalFloat" },
    NoicePopupBorder = { link = "FloatBorder" },
    NoiceConfirm = { link = "NormalFloat" },
    NoiceConfirmBorder = { link = "FloatBorder" },
    NoicePopupmenu = { link = "Pmenu" },
    NoicePopupmenuBorder = { link = "FloatBorder" },
    NoicePopupmenuSelected = { fg = p.text, bg = p.selection, bold = true },
    NoicePopupmenuMatch = { fg = p.pink, bold = true },
    NoiceSplit = { link = "NormalFloat" },
    NoiceSplitBorder = { link = "FloatBorder" },
    NoiceScrollbar = { bg = p.surface0 },
    NoiceScrollbarThumb = { bg = p.border },
    NoiceLspProgressSpinner = { fg = p.pink },
    NoiceLspProgressTitle = { fg = p.text },
    NoiceLspProgressClient = { fg = p.yellow },
    NoiceFormatLevelError = { fg = p.red, bg = p.error_bg },
    NoiceFormatLevelWarn = { fg = p.yellow, bg = p.warning_bg },
    NoiceFormatLevelInfo = { fg = p.blue, bg = p.info_bg },
    NoiceFormatLevelDebug = { fg = p.overlay1 },
    NoiceFormatLevelTrace = { fg = p.overlay1 },
    NoiceFormatTitle = { fg = p.yellow, bold = true },
    NoiceCompletionItemKindDefault = { fg = p.pink },

    NotifyBackground = { bg = p.base },
    NotifyERRORBorder = { fg = p.border_variant, bg = "NONE" },
    NotifyWARNBorder = { fg = p.border_variant, bg = "NONE" },
    NotifyINFOBorder = { fg = p.border_variant, bg = "NONE" },
    NotifyHINTBorder = { fg = p.border_variant, bg = "NONE" },
    NotifyDEBUGBorder = { fg = p.border_variant, bg = "NONE" },
    NotifyTRACEBorder = { fg = p.border_variant, bg = "NONE" },
    NotifyERRORIcon = { fg = p.red, bg = p.base },
    NotifyWARNIcon = { fg = p.yellow, bg = p.base },
    NotifyINFOIcon = { fg = p.blue, bg = p.base },
    NotifyDEBUGIcon = { fg = p.overlay1, bg = p.base },
    NotifyTRACEIcon = { fg = p.pink, bg = p.base },
    NotifyERRORTitle = { fg = p.red, bg = p.base },
    NotifyWARNTitle = { fg = p.yellow, bg = p.base },
    NotifyINFOTitle = { fg = p.blue, bg = p.base },
    NotifyDEBUGTitle = { fg = p.overlay1, bg = p.base },
    NotifyTRACETitle = { fg = p.pink, bg = p.base },
    NotifyERRORBody = { fg = p.text, bg = p.base },
    NotifyWARNBody = { fg = p.text, bg = p.base },
    NotifyINFOBody = { fg = p.text, bg = p.base },
    NotifyDEBUGBody = { fg = p.text, bg = p.base },
    NotifyTRACEBody = { fg = p.text, bg = p.base },
    NotifyLogTime = { fg = p.overlay1 },
    NotifyLogTitle = { fg = p.yellow },

    TelescopeBorder = { link = "FloatBorder" },
    TelescopeNormal = { link = "NormalFloat" },
    TelescopePreviewNormal = { link = "TelescopeNormal" },
    TelescopePromptNormal = { link = "TelescopeNormal" },
    TelescopeResultsNormal = { link = "TelescopeNormal" },
    TelescopeTitle = { link = "FloatTitle" },
    TelescopeSelection = { fg = p.text, bg = p.selection, bold = true },
    TelescopeSelectionCaret = { fg = p.pink, bg = p.selection },
    TelescopeMatching = { fg = p.pink, bold = true },
    TelescopePromptPrefix = { fg = p.pink },

    NvimTreeFolderName = { fg = p.yellow },
    NvimTreeFolderIcon = { fg = p.yellow },
    NvimTreeNormal = { fg = p.text, bg = p.mantle },
    NvimTreeNormalNC = { fg = p.text, bg = p.mantle },
    NvimTreeOpenedFolderName = { fg = p.yellow },
    NvimTreeEmptyFolderName = { fg = p.yellow },
    NvimTreeIndentMarker = { fg = p.border },
    NvimTreeWinSeparator = { fg = p.border_variant, bg = p.base },
    NvimTreeRootFolder = { fg = p.pink, bold = true },
    NvimTreeSymlink = { fg = p.pink },
    NvimTreeStatuslineNc = { fg = p.mantle, bg = p.mantle },
    NvimTreeGitDirty = { fg = p.yellow },
    NvimTreeGitNew = { fg = p.pink },
    NvimTreeGitDeleted = { fg = p.red },
    NvimTreeSpecialFile = { fg = p.pink },
    NvimTreeImageFile = { fg = p.text },
    NvimTreeOpenedFile = { fg = p.pink },

    SnacksNormal = { link = "Normal" },
    SnacksNormalNC = { link = "NormalFloat" },
    SnacksWinBar = { link = "Title" },
    SnacksWinBarNC = { link = "SnacksWinBar" },
    SnacksBackdrop = { fg = p.base, bg = p.base },
    SnacksWinSeparator = { link = "WinSeparator" },
    SnacksTitle = { link = "FloatTitle" },
    SnacksFooter = { link = "FloatFooter" },
    SnacksIndent = { fg = p.surface1 },
    SnacksIndentScope = { fg = p.overlay1 },

    SnacksInputNormal = { link = "NormalFloat" },
    SnacksInputBorder = { link = "FloatBorder" },
    SnacksInputTitle = { link = "FloatTitle" },

    SnacksNotifierInfo = { fg = p.blue, bg = p.base },
    SnacksNotifierIconInfo = { fg = p.blue, bg = p.base },
    SnacksNotifierTitleInfo = { fg = p.blue, bg = p.base, italic = true },
    SnacksNotifierBorderInfo = { fg = p.border_variant, bg = "NONE" },
    SnacksNotifierFooterInfo = { link = "DiagnosticInfo" },
    SnacksNotifierWarn = { fg = p.yellow, bg = p.base },
    SnacksNotifierIconWarn = { fg = p.yellow, bg = p.base },
    SnacksNotifierTitleWarn = { fg = p.yellow, bg = p.base, italic = true },
    SnacksNotifierBorderWarn = { fg = p.border_variant, bg = "NONE" },
    SnacksNotifierFooterWarn = { link = "DiagnosticWarn" },
    SnacksNotifierError = { fg = p.red, bg = p.base },
    SnacksNotifierIconError = { fg = p.red, bg = p.base },
    SnacksNotifierTitleError = { fg = p.red, bg = p.base, italic = true },
    SnacksNotifierBorderError = { fg = p.border_variant, bg = "NONE" },
    SnacksNotifierFooterError = { link = "DiagnosticError" },
    SnacksNotifierDebug = { fg = p.overlay1, bg = p.base },
    SnacksNotifierIconDebug = { fg = p.overlay1, bg = p.base },
    SnacksNotifierTitleDebug = { fg = p.overlay1, bg = p.base, italic = true },
    SnacksNotifierBorderDebug = { fg = p.border_variant, bg = "NONE" },
    SnacksNotifierFooterDebug = { link = "DiagnosticHint" },
    SnacksNotifierTrace = { fg = p.pink, bg = p.base },
    SnacksNotifierIconTrace = { fg = p.pink, bg = p.base },
    SnacksNotifierTitleTrace = { fg = p.pink, bg = p.base, italic = true },
    SnacksNotifierBorderTrace = { fg = p.border_variant, bg = "NONE" },
    SnacksNotifierFooterTrace = { link = "DiagnosticHint" },
    SnacksNotifierHistory = { link = "NormalFloat" },
    SnacksNotifierMinimal = { link = "NormalFloat" },

    SnacksDashboardNormal = { link = "Normal" },
    SnacksDashboardDesc = { fg = p.pink },
    SnacksDashboardFile = { fg = p.yellow },
    SnacksDashboardDir = { fg = p.overlay1 },
    SnacksDashboardFooter = { fg = p.yellow, italic = true },
    SnacksDashboardHeader = { fg = p.yellow },
    SnacksDashboardIcon = { fg = p.pink, bold = true },
    SnacksDashboardKey = { fg = p.yellow },
    SnacksDashboardSpecial = { fg = p.pink },
    SnacksDashboardTitle = { link = "Title" },

    SnacksPicker = { link = "NormalFloat" },
    SnacksPickerBorder = { link = "FloatBorder" },
    SnacksPickerInput = { link = "NormalFloat" },
    SnacksPickerInputBorder = { link = "FloatBorder" },
    SnacksPickerInputSearch = { fg = p.red },
    SnacksPickerPrompt = { fg = p.pink },
    SnacksPickerTitle = { fg = p.yellow, bg = p.base, bold = true },
    SnacksPickerPreviewTitle = { fg = p.pink, bg = p.base, bold = true },
    SnacksPickerInputTitle = { fg = p.red, bg = p.base, bold = true },
    SnacksPickerListTitle = { fg = p.yellow, bg = p.base, bold = true },
    SnacksPickerSelected = { fg = p.text, bg = p.selection, bold = true },
    SnacksPickerCursorLine = { fg = p.text, bg = p.selection },
    SnacksPickerListCursorLine = { fg = p.text, bg = p.selection },
    SnacksPickerPreviewCursorLine = { bg = p.selection },
    SnacksPickerMatch = { fg = p.pink, bold = true },
    SnacksPickerSearch = { link = "Search" },
    SnacksPickerSpecial = { fg = p.pink },
    SnacksPickerLabel = { fg = p.pink },
    SnacksPickerTotals = { fg = p.overlay1 },
    SnacksPickerFile = { fg = p.text },
    SnacksPickerDirectory = { fg = p.yellow },
    SnacksPickerPathIgnored = { fg = p.overlay0 },
    SnacksPickerPathHidden = { fg = p.overlay1 },
    SnacksPickerDir = { fg = p.overlay1 },
    SnacksPickerToggle = { fg = p.pink },
    SnacksPickerDimmed = { fg = p.overlay0 },
    SnacksPickerRow = { fg = p.yellow },
    SnacksPickerCol = { fg = p.overlay1 },
    SnacksPickerComment = { fg = p.overlay1, italic = true },
    SnacksPickerDesc = { fg = p.overlay1 },
    SnacksPickerDelim = { fg = p.overlay1 },
    SnacksPickerSpinner = { fg = p.pink },
    SnacksPickerUnselected = { fg = p.overlay0 },
    SnacksPickerIdx = { fg = p.yellow },
    SnacksPickerTree = { fg = p.overlay0 },
    SnacksPickerIcon = { fg = p.pink },
    SnacksPickerIconSource = { fg = p.yellow },
    SnacksPickerIconName = { fg = p.red },
    SnacksPickerIconCategory = { fg = p.yellow },
    SnacksPickerGitStatusAdded = { fg = p.pink },
    SnacksPickerGitStatusModified = { fg = p.yellow },
    SnacksPickerGitStatusDeleted = { fg = p.red },
    SnacksPickerGitStatusRenamed = { fg = p.text },
    SnacksPickerGitStatusUntracked = { fg = p.overlay1 },
    SnacksPickerGitStatusIgnored = { fg = p.overlay0 },
    SnacksPickerGitStatusStaged = { fg = p.pink },
    SnacksPickerGitStatusUnmerged = { fg = p.red },

    WhichKey = { link = "NormalFloat" },
    WhichKeyNormal = { link = "NormalFloat" },
    WhichKeyBorder = { link = "FloatBorder" },
    WhichKeyTitle = { link = "FloatTitle" },
    WhichKeyDesc = { fg = p.yellow },
    WhichKeyGroup = { fg = p.pink },
    WhichKeySeparator = { fg = p.overlay1 },
    WhichKeyValue = { fg = p.overlay1 },
    WhichKeyIcon = { fg = p.pink },
    WhichKeyIconAzure = { fg = p.blue },
    WhichKeyIconBlue = { fg = p.blue },
    WhichKeyIconCyan = { fg = p.teal },
    WhichKeyIconGreen = { fg = p.yellow },
    WhichKeyIconGrey = { fg = p.text },
    WhichKeyIconOrange = { fg = p.yellow },
    WhichKeyIconPurple = { fg = p.pink },
    WhichKeyIconRed = { fg = p.red },
    WhichKeyIconYellow = { fg = p.yellow },

    MiniIconsAzure = { fg = p.blue },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.teal },
    MiniIconsGreen = { fg = p.yellow },
    MiniIconsGrey = { fg = p.text },
    MiniIconsOrange = { fg = p.yellow },
    MiniIconsPurple = { fg = p.pink },
    MiniIconsRed = { fg = p.red },
    MiniIconsYellow = { fg = p.yellow },
  }
end

function M.setup(variant)
  local p = palettes[variant] or palettes.night

  vim.opt.termguicolors = true
  vim.opt.background = p.background
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.g.colors_name = variant == "light" and "fate-astolfo-light" or "fate-astolfo-night"

  apply({
    editor(p),
    syntax(p),
    diagnostics(p),
    lualine(p),
    treesitter(p),
    integrations(p),
  })

  link("DiagnosticSignError", "DiagnosticError")
  link("DiagnosticSignWarn", "DiagnosticWarn")
  link("DiagnosticSignInfo", "DiagnosticInfo")
  link("DiagnosticSignHint", "DiagnosticHint")
  link("DiagnosticFloatBorder", "FloatBorder")
  link("LspInfoBorder", "FloatBorder")

  for name, value in pairs(terminal(p)) do
    vim.g[name] = value
  end
end

return M
